# Generated by Django 3.0 on 2020-02-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200220_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CategoriaResumo'),
        ),
    ]
