# Generated by Django 3.0 on 2020-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200221_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
